- name: OCP Post installation tasks
  hosts: localhost
  gather_facts: yes
  module_defaults:
    group/kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig }}"
  roles:
    - name: 00. setup cluster
      role: setup
    - name: 01. Create infra and ODF machinesets
      role: create-machinesets
    - name: 02. Create infra and odf MCP
      role: create-mcp
    - name: 03. Migrate default ingress controller and registry to infra nodes
      role: migrate
    - name: 04. Disabling project self provisioning
      role: disable-self-provision
    - name: 05. Config localusers htpasswd identity provider
      role: htpasswd-provider
    - name: 06. Configure OAuth with Active Directory
      role: ldap-provider
    - name: 07. Remove default kubeadmin user
      role: remove-kubeadmin
