- name: Migrate image registry to infra nodes
  kubernetes.core.k8s:
    api_version: imageregistry.operator.openshift.io/v1
    kubeconfig: "{{ kubeconfig }}"
    state: patched
    name: "cluster"
    kind: "Config"
    definition:
      spec:
        nodeSelector:
          node-role.kubernetes.io/infra: ""
        tolerations:
          - key: "node-role.kubernetes.io/infra"
            operator: "Exists"
            effect: "NoSchedule"
        managementState: Managed
        storage:
          emptyDir: {}

- name: Migrate ingress controller to infra nodes
  kubernetes.core.k8s:
    api_version: operator.openshift.io/v1
    kubeconfig: "{{ kubeconfig }}"
    state: patched
    name: "default"
    namespace: "openshift-ingress-operator"
    kind: "IngressController"
    definition:
      spec:
        nodePlacement:
          nodeSelector:
            matchLabels:
              node-role.kubernetes.io/infra: ""
          tolerations:
            - key: "node-role.kubernetes.io/infra"
              operator: "Exists"
              effect: "NoSchedule"
