- name: Apply MachineConfig for {{ item }}
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      metadata:
        name: "99-{{ item }}-chrony"
        labels:
          machineconfiguration.openshift.io/role: "{{ item }}"
      spec:
        config:
          ignition:
            version: 3.2.0
          storage:
            files:
              - path: /etc/chrony.conf
                mode: 0644
                contents:
                  source: data:,pool%20time1.google.com%20iburst%0Apool%20time2.google.com%20iburst%0A
  loop:
    - master
    - worker
    - infra
    - odf

- name: Wait for 5 minutes to let the master reboot
  pause:
    minutes: 5

- name: Wait for MCP {{ item }} to finish updating
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: "{{ item }}"
  register: mcp
  retries: 60
  delay: 30
  until:
    - >
      (
        mcp.resources[0].status.conditions
        | selectattr('type', 'equalto', 'Updated')
        | map(attribute='status')
        | first
      ) == "True"

    - >
      (
        mcp.resources[0].status.conditions
        | selectattr('type', 'equalto', 'Updating')
        | map(attribute='status')
        | first
      ) == "False"

    - >
      (
        mcp.resources[0].status.conditions
        | selectattr('type', 'equalto', 'Degraded')
        | map(attribute='status')
        | first
      ) == "False"
  loop:
    - master
    - worker
    - infra
    - odf
