- name: Install required python packages
  apt:
    name:
      - python3-kubernetes
      - python3-ldap
    state: present

- name: Create neccessary directories on master
  file:
    state: directory
    path: "{{ item }}"
    owner: core
    group: core
  loop:
    - "{{ master_dir }}"
    - "{{ master_dir }}/01-mcp"
    - "{{ master_dir }}/05-htpass-users"
    - "{{ master_dir }}/08-ldap-sync"
    - "{{ master_dir }}/11-ingress-cert"
    - "{{ master_dir }}/12-api-cert"
  delegate_to: "{{ groups['masters'][0] }}"

- name: Create neccessary directories locally
  file:
    state: directory
    path: "{{ item }}"
  become: True
  loop:
    - "{{ dir }}"
    - "{{ dir }}/01-mcp"
    - "{{ dir }}/05-htpass-users"
    - "{{ dir }}/06-ldap-provider"
    - "{{ dir }}/08-ldap-sync"
    - "{{ dir }}/11-ingress-cert"
    - "{{ dir }}/12-api-cert"

- name: Copy kubeconfig to master
  copy:
    src: "{{ kubeconfig }}"
    dest: /home/core/kube
    owner: core
    group: core
    mode: "0600"
  delegate_to: "{{ groups['masters'][0] }}"

- name: Get all CSRs
  kubernetes.core.k8s_info:
    api_version: certificates.k8s.io/v1
    kind: CertificateSigningRequest
  register: csr_list

- name: Approve pending CSRs
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: certificates.k8s.io/v1
      kind: CertificateSigningRequest
      metadata:
        name: "{{ item.metadata.name }}"
      status:
        conditions:
          - type: Approved
            status: "True"
            reason: AnsibleApprove
            message: "Approved by Ansible"
  loop: "{{ csr_list.resources }}"
  when: item.status.conditions is not defined

- name: Copy kubeconfig to master(default kubeconfig path)
  copy:
    src: "{{ kubeconfig }}"
    dest: ~/.kube/config
    owner: core
    group: core
    mode: "0600"
  delegate_to: "{{ groups['masters'][0] }}"

# Install helm
- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0755"

- name: Run Helm install script
  command: /tmp/get_helm.sh
